# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1119, 751)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tab_account = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tab_account.setGeometry(QtCore.QRect(10, 10, 1101, 731))
        self.tab_account.setObjectName("tab_account")
        self.Account = QtWidgets.QWidget()
        self.Account.setObjectName("Account")
        self.list_account_ac = QtWidgets.QListWidget(parent=self.Account)
        self.list_account_ac.setGeometry(QtCore.QRect(600, 100, 400, 500))
        self.list_account_ac.setObjectName("list_account_ac")
        self.add_account = QtWidgets.QPushButton(parent=self.Account)
        self.add_account.setGeometry(QtCore.QRect(230, 20, 150, 40))
        self.add_account.setObjectName("add_account")
        self.account_input_add = QtWidgets.QLineEdit(parent=self.Account)
        self.account_input_add.setGeometry(QtCore.QRect(20, 20, 200, 40))
        self.account_input_add.setObjectName("account_input_add")
        self.remove_account_input = QtWidgets.QLineEdit(parent=self.Account)
        self.remove_account_input.setGeometry(QtCore.QRect(20, 70, 200, 40))
        self.remove_account_input.setObjectName("remove_account_input")
        self.remove_account_bot = QtWidgets.QPushButton(parent=self.Account)
        self.remove_account_bot.setGeometry(QtCore.QRect(230, 70, 150, 40))
        self.remove_account_bot.setObjectName("remove_account_bot")
        self.help_account_add = QtWidgets.QTextBrowser(parent=self.Account)
        self.help_account_add.setGeometry(QtCore.QRect(20, 120, 461, 81))
        self.help_account_add.setObjectName("help_account_add")
        self.help_remove_account = QtWidgets.QTextBrowser(parent=self.Account)
        self.help_remove_account.setGeometry(QtCore.QRect(20, 200, 461, 81))
        self.help_remove_account.setObjectName("help_remove_account")
        self.textBrowser_2 = QtWidgets.QTextBrowser(parent=self.Account)
        self.textBrowser_2.setGeometry(QtCore.QRect(600, 60, 400, 40))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.lcdNumber = QtWidgets.QLCDNumber(parent=self.Account)
        self.lcdNumber.setGeometry(QtCore.QRect(600, 610, 200, 80))
        self.lcdNumber.setObjectName("lcdNumber")
        self.update_number_bot = QtWidgets.QPushButton(parent=self.Account)
        self.update_number_bot.setGeometry(QtCore.QRect(820, 610, 150, 40))
        self.update_number_bot.setObjectName("update_number_bot")
        self.tab_account.addTab(self.Account, "")
        self.joingaps = QtWidgets.QWidget()
        self.joingaps.setObjectName("joingaps")
        self.textEdit = QtWidgets.QTextEdit(parent=self.joingaps)
        self.textEdit.setGeometry(QtCore.QRect(20, 100, 400, 200))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(parent=self.joingaps)
        self.pushButton.setGeometry(QtCore.QRect(20, 310, 150, 40))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.joingaps)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 310, 150, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.joingaps)
        self.pushButton_3.setGeometry(QtCore.QRect(340, 310, 150, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.comboBox = QtWidgets.QComboBox(parent=self.joingaps)
        self.comboBox.setGeometry(QtCore.QRect(20, 60, 200, 40))
        self.comboBox.setObjectName("comboBox")
        self.groupBox = QtWidgets.QGroupBox(parent=self.joingaps)
        self.groupBox.setGeometry(QtCore.QRect(20, 360, 470, 200))
        self.groupBox.setObjectName("groupBox")
        self.gap_count_label = QtWidgets.QLabel(parent=self.groupBox)
        self.gap_count_label.setGeometry(QtCore.QRect(19, 30, 201, 40))
        self.gap_count_label.setObjectName("gap_count_label")
        self.gap_count_spinbox = QtWidgets.QSpinBox(parent=self.groupBox)
        self.gap_count_spinbox.setGeometry(QtCore.QRect(230, 30, 150, 40))
        self.gap_count_spinbox.setMinimum(1)
        self.gap_count_spinbox.setMaximum(100)
        self.gap_count_spinbox.setObjectName("gap_count_spinbox")
        self.joingaps_help = QtWidgets.QTextBrowser(parent=self.joingaps)
        self.joingaps_help.setGeometry(QtCore.QRect(600, 60, 400, 500))
        self.joingaps_help.setObjectName("joingaps_help")
        self.tab_account.addTab(self.joingaps, "")
        self.banners = QtWidgets.QWidget()
        self.banners.setObjectName("banners")
        self.banner_list = QtWidgets.QListWidget(parent=self.banners)
        self.banner_list.setGeometry(QtCore.QRect(20, 100, 400, 500))
        self.banner_list.setObjectName("banner_list")
        self.show_banner_button = QtWidgets.QPushButton(parent=self.banners)
        self.show_banner_button.setGeometry(QtCore.QRect(430, 100, 150, 40))
        self.show_banner_button.setObjectName("show_banner_button")
        self.delete_banner_button = QtWidgets.QPushButton(parent=self.banners)
        self.delete_banner_button.setGeometry(QtCore.QRect(430, 150, 150, 40))
        self.delete_banner_button.setObjectName("delete_banner_button")
        self.banner_name_input = QtWidgets.QLineEdit(parent=self.banners)
        self.banner_name_input.setGeometry(QtCore.QRect(20, 20, 200, 40))
        self.banner_name_input.setObjectName("banner_name_input")
        self.banner_text_input = QtWidgets.QTextEdit(parent=self.banners)
        self.banner_text_input.setGeometry(QtCore.QRect(230, 20, 350, 60))
        self.banner_text_input.setProperty("maxLength", 4048)
        self.banner_text_input.setObjectName("banner_text_input")
        self.add_banner_button = QtWidgets.QPushButton(parent=self.banners)
        self.add_banner_button.setGeometry(QtCore.QRect(590, 20, 150, 40))
        self.add_banner_button.setObjectName("add_banner_button")
        self.banner_help = QtWidgets.QTextBrowser(parent=self.banners)
        self.banner_help.setGeometry(QtCore.QRect(600, 100, 400, 500))
        self.banner_help.setObjectName("banner_help")
        self.tab_account.addTab(self.banners, "")
        self.sending = QtWidgets.QWidget()
        self.sending.setObjectName("sending")
        self.send_interval_label = QtWidgets.QLabel(parent=self.sending)
        self.send_interval_label.setGeometry(QtCore.QRect(20, 80, 200, 40))
        self.send_interval_label.setObjectName("send_interval_label")
        self.send_interval_spinbox = QtWidgets.QSpinBox(parent=self.sending)
        self.send_interval_spinbox.setGeometry(QtCore.QRect(230, 80, 150, 40))
        self.send_interval_spinbox.setMinimum(1)
        self.send_interval_spinbox.setMaximum(1440)
        self.send_interval_spinbox.setObjectName("send_interval_spinbox")
        self.send_interval_current = QtWidgets.QLabel(parent=self.sending)
        self.send_interval_current.setGeometry(QtCore.QRect(390, 80, 150, 40))
        self.send_interval_current.setObjectName("send_interval_current")
        self.account_interval_label = QtWidgets.QLabel(parent=self.sending)
        self.account_interval_label.setGeometry(QtCore.QRect(20, 130, 200, 40))
        self.account_interval_label.setObjectName("account_interval_label")
        self.account_interval_spinbox = QtWidgets.QSpinBox(parent=self.sending)
        self.account_interval_spinbox.setGeometry(QtCore.QRect(230, 130, 150, 40))
        self.account_interval_spinbox.setMinimum(1)
        self.account_interval_spinbox.setMaximum(1440)
        self.account_interval_spinbox.setObjectName("account_interval_spinbox")
        self.account_interval_current = QtWidgets.QLabel(parent=self.sending)
        self.account_interval_current.setGeometry(QtCore.QRect(390, 130, 150, 40))
        self.account_interval_current.setObjectName("account_interval_current")
        self.rest_interval_label = QtWidgets.QLabel(parent=self.sending)
        self.rest_interval_label.setGeometry(QtCore.QRect(20, 180, 200, 40))
        self.rest_interval_label.setObjectName("rest_interval_label")
        self.rest_interval_spinbox = QtWidgets.QSpinBox(parent=self.sending)
        self.rest_interval_spinbox.setGeometry(QtCore.QRect(230, 180, 150, 40))
        self.rest_interval_spinbox.setMinimum(1)
        self.rest_interval_spinbox.setMaximum(1440)
        self.rest_interval_spinbox.setObjectName("rest_interval_spinbox")
        self.rest_interval_current = QtWidgets.QLabel(parent=self.sending)
        self.rest_interval_current.setGeometry(QtCore.QRect(390, 180, 150, 40))
        self.rest_interval_current.setObjectName("rest_interval_current")
        self.save_intervals_button = QtWidgets.QPushButton(parent=self.sending)
        self.save_intervals_button.setGeometry(QtCore.QRect(230, 230, 150, 40))
        self.save_intervals_button.setObjectName("save_intervals_button")
        self.sending_help = QtWidgets.QTextBrowser(parent=self.sending)
        self.sending_help.setGeometry(QtCore.QRect(600, 60, 400, 500))
        self.sending_help.setObjectName("sending_help")
        self.tab_account.addTab(self.sending, "")
        self.manage = QtWidgets.QWidget()
        self.manage.setObjectName("manage")
        self.report_details = QtWidgets.QTextEdit(parent=self.manage)
        self.report_details.setGeometry(QtCore.QRect(20, 480, 560, 200))
        self.report_details.setObjectName("report_details")
        self.toggle_auto_send_button = QtWidgets.QPushButton(parent=self.manage)
        self.toggle_auto_send_button.setGeometry(QtCore.QRect(600, 50, 150, 40))
        self.toggle_auto_send_button.setObjectName("toggle_auto_send_button")
        self.auto_send_status_label = QtWidgets.QLabel(parent=self.manage)
        self.auto_send_status_label.setGeometry(QtCore.QRect(760, 50, 200, 40))
        self.auto_send_status_label.setObjectName("auto_send_status_label")
        self.generate_stats_button = QtWidgets.QPushButton(parent=self.manage)
        self.generate_stats_button.setGeometry(QtCore.QRect(20, 120, 150, 40))
        self.generate_stats_button.setObjectName("generate_stats_button")
        self.manage_help = QtWidgets.QTextBrowser(parent=self.manage)
        self.manage_help.setGeometry(QtCore.QRect(600, 100, 400, 500))
        self.manage_help.setObjectName("manage_help")
        self.report_gen = QtWidgets.QTextEdit(parent=self.manage)
        self.report_gen.setGeometry(QtCore.QRect(20, 170, 560, 301))
        self.report_gen.setObjectName("report_gen")
        self.tab_account.addTab(self.manage, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tab_account.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Telegram Auto Sender & Scheduler By https://erfan4lx.com"))
        MainWindow.setWindowIcon(QtGui.QIcon("icon.jpg"))
        MainWindow.setStyleSheet(_translate("MainWindow", "font-family: \"Segoe UI\"; font-size: 10pt; QMainWindow { background-color: #2c2c2c; } QPushButton { background-color: #4a4a4a; color: white; border-radius: 5px; padding: 5px; } QPushButton:hover { background-color: #606060; } QLineEdit, QTextEdit, QSpinBox, QComboBox { background-color: #3c3c3c; color: white; border: 1px solid #555555; border-radius: 5px; padding: 5px; } QTabWidget::pane { border: 1px solid #555555; } QTabWidget::tab { background-color: #3c3c3c; color: white; padding: 8px; } QTabWidget::tab:selected { background-color: #4a4a4a; color: white; } QLabel, QGroupBox { color: white; } QListWidget, QTextBrowser, QLCDNumber { background-color: #3c3c3c; color: white; border: 1px solid #555555; border-radius: 5px; }"))
        self.tab_account.setStyleSheet(_translate("MainWindow", "QTabWidget::pane { border: 1px solid #555555; background: #2c2c2c; } QTabWidget::tab { background: #3c3c3c; padding: 10px; color: white; } QTabWidget::tab:selected { background: #4a4a4a; color: white; }"))
        self.list_account_ac.setStyleSheet(_translate("MainWindow", "border: 1px solid #555555; border-radius: 5px; background-color: #3c3c3c; color: white;"))
        self.add_account.setText(_translate("MainWindow", "Add account"))
        self.account_input_add.setText(_translate("MainWindow", "+123456789"))
        self.account_input_add.setPlaceholderText(_translate("MainWindow", "Enter account number"))
        self.remove_account_input.setText(_translate("MainWindow", "+123456789"))
        self.remove_account_input.setPlaceholderText(_translate("MainWindow", "Enter account to remove"))
        self.remove_account_bot.setText(_translate("MainWindow", "Remove account"))
        self.help_account_add.setStyleSheet(_translate("MainWindow", "border: 1px solid #555555; border-radius: 5px; background: #3c3c3c; color: white;"))
        self.help_account_add.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Add Account</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Enter a valid account number and click &quot;Add account&quot; to include it in the list.</p></body></html>"))
        self.help_remove_account.setStyleSheet(_translate("MainWindow", "border: 1px solid #555555; border-radius: 5px; background: #3c3c3c; color: white;"))
        self.help_remove_account.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Remove Account</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Enter an account number and click &quot;Remove account&quot; to delete it from the list.</p></body></html>"))
        self.textBrowser_2.setStyleSheet(_translate("MainWindow", "border: 1px solid #555555; border-radius: 5px; background: #3c3c3c; color: white;"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">List Accounts</span></p></body></html>"))
        self.lcdNumber.setStyleSheet(_translate("MainWindow", "border: 1px solid #555555; border-radius: 5px; background: #3c3c3c; color: white;"))
        self.update_number_bot.setText(_translate("MainWindow", "Update Number"))
        self.tab_account.setTabText(self.tab_account.indexOf(self.Account), _translate("MainWindow", "Accounts"))
        self.textEdit.setStyleSheet(_translate("MainWindow", "border: 1px solid #555555; border-radius: 5px; background-color: #3c3c3c; color: white;"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "Enter group links of lines"))
        self.pushButton.setText(_translate("MainWindow", "Join All Accounts"))
        self.pushButton_2.setText(_translate("MainWindow", "Join Selected Account"))
        self.pushButton_3.setText(_translate("MainWindow", "Clear Links"))
        self.comboBox.setProperty("placeholderText", _translate("MainWindow", "Select account"))
        self.groupBox.setStyleSheet(_translate("MainWindow", "border: 1px solid #555555; border-radius: 5px; background-color: #2c2c2c; color: white;"))
        self.groupBox.setTitle(_translate("MainWindow", "Gap Settings"))
        self.gap_count_label.setText(_translate("MainWindow", "time sleep of join groups: (minutes)"))
        self.joingaps_help.setStyleSheet(_translate("MainWindow", "border: 1px solid #555555; border-radius: 5px; background: #3c3c3c; color: white;"))
        self.joingaps_help.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Join Groups Help</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1. Select an account from the dropdown menu.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2. Enter gap link in the text area.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3. Set the sleep of join in the group Settings section.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">4. Click &quot;Join All Accounts&quot; or &quot;Join Selected Account&quot; to apply changes, or &quot;Clear Links&quot; to reset.</p></body></html>"))
        self.tab_account.setTabText(self.tab_account.indexOf(self.joingaps), _translate("MainWindow", "Join Groups"))
        self.banner_list.setStyleSheet(_translate("MainWindow", "border: 1px solid #555555; border-radius: 5px; background-color: #3c3c3c; color: white;"))
        self.show_banner_button.setText(_translate("MainWindow", "Show Banner"))
        self.delete_banner_button.setText(_translate("MainWindow", "Delete Banner"))
        self.banner_name_input.setPlaceholderText(_translate("MainWindow", "Enter banner name"))
        self.banner_text_input.setStyleSheet(_translate("MainWindow", "border: 1px solid #555555; border-radius: 5px; background-color: #3c3c3c; color: white;"))
        self.banner_text_input.setPlaceholderText(_translate("MainWindow", "Enter banner text (max 4048 characters)"))
        self.add_banner_button.setText(_translate("MainWindow", "Add Banner"))
        self.banner_help.setStyleSheet(_translate("MainWindow", "border: 1px solid #555555; border-radius: 5px; background: #3c3c3c; color: white;"))
        self.banner_help.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Banner Management Help</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1. Enter a unique name for the banner in the &quot;Banner Name&quot; field.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2. Enter the banner text (up to 4048 characters) in the text area.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3. Click &quot;Add Banner&quot; to save the banner to the list.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">4. Select a banner from the list and use &quot;Show Banner&quot; to view it or &quot;Delete Banner&quot; to remove it.</p></body></html>"))
        self.tab_account.setTabText(self.tab_account.indexOf(self.banners), _translate("MainWindow", "Message Templates"))
        self.send_interval_label.setText(_translate("MainWindow", "Send Interval (second):"))
        self.send_interval_current.setStyleSheet(_translate("MainWindow", "font-style: italic; color: white;"))
        self.send_interval_current.setText(_translate("MainWindow", "Current: Not set"))
        self.account_interval_label.setText(_translate("MainWindow", "Account Interval (minutes):"))
        self.account_interval_current.setStyleSheet(_translate("MainWindow", "font-style: italic; color: white;"))
        self.account_interval_current.setText(_translate("MainWindow", "Current: Not set"))
        self.rest_interval_label.setText(_translate("MainWindow", "Rest Interval (minutes):"))
        self.rest_interval_current.setStyleSheet(_translate("MainWindow", "font-style: italic; color: white;"))
        self.rest_interval_current.setText(_translate("MainWindow", "Current: Not set"))
        self.save_intervals_button.setText(_translate("MainWindow", "Save Intervals"))
        self.sending_help.setStyleSheet(_translate("MainWindow", "border: 1px solid #555555; border-radius: 5px; background: #3c3c3c; color: white;"))
        self.sending_help.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Sending Settings Help</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1. Set the interval between sends (in minutes) using the &quot;Send Interval&quot; field. Current value is displayed next to it.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2. Set the interval between accounts (in minutes) using the &quot;Account Interval&quot; field. Current value is displayed next to it.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3. Set the rest interval (in minutes) using the &quot;Rest Interval&quot; field. Current value is displayed next to it.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">4. Click &quot;Save Intervals&quot; to apply the settings.</p></body></html>"))
        self.tab_account.setTabText(self.tab_account.indexOf(self.sending), _translate("MainWindow", "Sending Scheduler"))
        self.report_details.setStyleSheet(_translate("MainWindow", "border: 1px solid #555555; border-radius: 5px; background-color: #3c3c3c; color: white;"))
        self.report_details.setPlaceholderText(_translate("MainWindow", "View report details here"))
        self.toggle_auto_send_button.setStyleSheet(_translate("MainWindow", "background-color: #1e7e34; border-radius: 5px; color: white;"))
        self.toggle_auto_send_button.setText(_translate("MainWindow", "Toggle Auto-Send"))
        self.auto_send_status_label.setStyleSheet(_translate("MainWindow", "font-weight: bold; font-size: 12pt; color: white;"))
        self.auto_send_status_label.setText(_translate("MainWindow", "Auto-Send: Off"))
        self.generate_stats_button.setStyleSheet(_translate("MainWindow", "background-color: #138496; border-radius: 5px; color: white;"))
        self.generate_stats_button.setText(_translate("MainWindow", "Generate Statistics"))
        self.manage_help.setStyleSheet(_translate("MainWindow", "border: 1px solid #555555; border-radius: 5px; background: #3c3c3c; color: white;"))
        self.manage_help.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Manage Settings Help</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1. Click &quot;Toggle Auto-Send&quot; to enable or disable automatic sending. The current status is displayed next to it.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2. View reports in the table and detailed information in the text box below.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3. Click &quot;Generate Statistics&quot; to run a background statistics process.</p></body></html>"))
        self.report_gen.setStyleSheet(_translate("MainWindow", "border: 1px solid #555555; border-radius: 5px; background-color: #3c3c3c; color: white;"))
        self.report_gen.setPlaceholderText(_translate("MainWindow", "View report statistics here"))
        self.tab_account.setTabText(self.tab_account.indexOf(self.manage), _translate("MainWindow", "Manage"))
